---
name: Check Public API for Breaking Changes
on:
  pull_request:
    branches: [main]
jobs:
  check-api-for-breaking-changes:
    uses: tektronix/tm_devices/.github/workflows/check-api-for-breaking-changes.yml@main
    with:
      package-name: tm_data_types
