---
name: Pull Request Dependency Review
on:
  pull_request:
    branches: [main]
jobs:
  dependency-review:
    uses: tektronix/tm_devices/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: write
