---
name: Package Release
on:
  workflow_dispatch:
    inputs:
      release_level:
        type: choice
        required: true
        description: |
          Select the release level,
          patch for backward compatible minor changes and bug fixes,
          minor for backward compatible larger changes,
          major for non-backward compatible changes.
        options: [patch, minor, major]
concurrency:
  group: pypi
jobs:
  package-release:
    uses: tektronix/tm_devices/.github/workflows/package-release.yml@main
    with:
      package-name: tm_data_types
      release_level: ${{ inputs.release_level }}
    permissions:
      id-token: write
      contents: write
    secrets: inherit
