---
# Upload to Test PyPI on every push to main
name: Publish to TestPyPI
on:
  push:
    branches: [main]
concurrency:
  group: pypi
jobs:
  package-testpypi:
    uses: tektronix/tm_devices/.github/workflows/package-testpypi.yml@main
    with:
      package-name: tm_data_types
    permissions:
      id-token: write
      attestations: write
