---
name: Package Build
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]
jobs:
  package-build:
    uses: tektronix/tm_devices/.github/workflows/package-build.yml@main
    with:
      package-name: tm_data_types
    permissions:
      id-token: write
      attestations: write
