---
name: Publish API Breaking Change Check Results
on:
  workflow_run:
    workflows: [Check Public API for Breaking Changes]
    types: [completed]
jobs:
  publish-api-comparison:
    uses: tektronix/tm_devices/.github/workflows/publish-test-results.yml@main
    permissions:
      checks: write
      pull-requests: write
