---
name: Create & Scan SBOM
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
jobs:
  sbom-scan:
    uses: tektronix/tm_devices/.github/workflows/sbom-scan.yml@main
    permissions:
      security-events: write
      contents: write
      id-token: write
      attestations: write
