---
name: Test docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-caller-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test-docs:
    uses: tektronix/tm_devices/.github/workflows/test-docs.yml@main
    with:
      node-version: 20  # The node version needs to stay in sync with .readthedocs.yml
      python-version: '3.11'  # This needs to stay in sync with .readthedocs.yml and the tox config in pyproject.toml
